### ISSUE TITLE
not install 

### ISSUE THREAD

**Issue by hamelhmc** [CodelyTV/dotfiles#12]
`Traceback (most recent call last):
  File "/Users/hamel/.dotfiles/modules/dotbot/bin/dotbot", line 39, in <module>
    import dotbot
  File "/Users/hamel/.dotfiles/modules/dotbot/dotbot/__init__.py", line 1, in <module>
    from .cli import main
  File "/Users/hamel/.dotfiles/modules/dotbot/dotbot/cli.py", line 5, in <module>
    from .config import ConfigReader, ReadingError
  File "/Users/hamel/.dotfiles/modules/dotbot/dotbot/config.py", line 1, in <module>
    import yaml
  File "/Users/hamel/.dotfiles/modules/dotbot/lib/pyyaml/lib/yaml/__init__.py", line 362
    class YAMLObject(metaclass=YAMLObjectMetaclass):`

**Comment by racastellanosm** [comment]
Same problem here:
MacOS - BigSur 
Chip: Intel
Model: MacBook Pro 2020 

```
Submodule path 'modules/zimfw': merged in 'de685e8ef3846bc69847bf5281fcb7adb8ad096c'
Applying common Symlinks

Traceback (most recent call last):
  File "/Users/*******/.dotfiles/modules/dotbot/bin/dotbot", line 39, in <module>
    import dotbot
  File "/Users/*******/.dotfiles/modules/dotbot/dotbot/__init__.py", line 1, in <module>
    from .cli import main
  File "/Users/*******/.dotfiles/modules/dotbot/dotbot/cli.py", line 5, in <module>
    from .config import ConfigReader, ReadingError
  File "/Users/*******/.dotfiles/modules/dotbot/dotbot/config.py", line 1, in <module>
    import yaml
  File "/Users/*******/.dotfiles/modules/dotbot/lib/pyyaml/lib/yaml/__init__.py", line 362
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
```

**Comment by joserojasrodriguez** [comment]
Same problem
